version: '3.3'
services:
  redis:
    image: "redis:alpine"
    command: "redis-server --appendonly yes --port 6480"
    ports:
      - "6480:6480"
    volumes:
      - ./redis:/data
    restart: "always"
  app:
    build:
      context: ./app
      dockerfile: app.dockerfile
    volumes:
      - ./app:/app
